import { motion } from 'framer-motion';
import { Shield, ChevronLeft } from 'lucide-react';
import { Link } from 'react-router-dom';

const LAST_UPDATED = 'May 16, 2025';
const CONTACT_EMAIL = 'singhkapoortech@gmail.com';

interface SectionProps {
  title: string;
  children: React.ReactNode;
}

function Section({ title, children }: SectionProps) {
  return (
    <motion.section
      initial={{ opacity: 0, y: 16 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ duration: 0.4 }}
      className="space-y-3"
    >
      <h2 className="text-xl font-semibold text-slate-100">{title}</h2>
      <div className="text-slate-400 leading-relaxed space-y-3">{children}</div>
    </motion.section>
  );
}

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-slate-950 text-slate-100">
      {/* Header */}
      <header className="border-b border-slate-800 bg-slate-900/80 backdrop-blur sticky top-0 z-10">
        <div className="container mx-auto max-w-3xl px-6 py-4 flex items-center gap-4">
          <Link
            to="/"
            className="flex items-center gap-1.5 text-sm text-slate-400 hover:text-slate-100 transition-colors"
          >
            <ChevronLeft className="w-4 h-4" />
            Back
          </Link>
          <div className="flex items-center gap-2 ml-auto">
            <div className="w-7 h-7 rounded-lg bg-gradient-to-br from-indigo-500 to-violet-500 flex items-center justify-center">
              <Shield className="w-4 h-4 text-white" />
            </div>
            <span className="font-semibold">Divit Privacy Policy</span>
          </div>
        </div>
      </header>

      <main className="container mx-auto max-w-3xl px-6 py-12 space-y-10">
        {/* Hero */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="space-y-3"
        >
          <h1 className="text-4xl font-bold bg-gradient-to-r from-indigo-400 via-violet-400 to-cyan-400 bg-clip-text text-transparent">
            Privacy Policy
          </h1>
          <p className="text-slate-400">Last updated: {LAST_UPDATED}</p>
          <p className="text-slate-300 text-lg leading-relaxed">
            Divit helps friends split bills fairly. We keep your data simple, secure, and
            under your control. This policy explains exactly what we collect, why we collect
            it, and what you can do about it.
          </p>
        </motion.div>

        <div className="h-px bg-slate-800" />

        {/* 1 */}
        <Section title="1. Who We Are">
          <p>
            Divit is an app for splitting restaurant bills, trip expenses, and shared costs
            with friends. It is operated independently and can be reached at{' '}
            <a href={`mailto:${CONTACT_EMAIL}`} className="text-indigo-400 hover:underline">
              {CONTACT_EMAIL}
            </a>
            .
          </p>
        </Section>

        {/* 2 */}
        <Section title="2. Information We Collect">
          <p className="font-medium text-slate-200">When you sign in:</p>
          <ul className="list-disc list-inside space-y-1 pl-2">
            <li>Your name and email address from your Google account</li>
            <li>A unique user ID generated by Firebase Authentication</li>
          </ul>

          <p className="font-medium text-slate-200 pt-2">When you use the app:</p>
          <ul className="list-disc list-inside space-y-1 pl-2">
            <li>
              <span className="text-slate-200">Venmo handle</span> — only if you choose to
              add one; used to generate payment request links
            </li>
            <li>
              <span className="text-slate-200">Friends and Squads</span> — names and Venmo
              handles you enter for the people you split with
            </li>
            <li>
              <span className="text-slate-200">Bill data</span> — item names, prices, tax,
              tip, and who owes what
            </li>
            <li>
              <span className="text-slate-200">Receipt images</span> — photos you upload to
              scan a bill automatically (see Section 4)
            </li>
            <li>
              <span className="text-slate-200">Event and balance data</span> — group events,
              shared ledgers, and settlement records between linked friends
            </li>
          </ul>

          <p className="font-medium text-slate-200 pt-2">Automatically collected:</p>
          <ul className="list-disc list-inside space-y-1 pl-2">
            <li>
              Basic usage analytics via Firebase Analytics (screen views, feature usage) to
              help us improve the app
            </li>
            <li>Standard server logs (IP address, timestamps) retained by Firebase and Vercel</li>
          </ul>
        </Section>

        {/* 3 */}
        <Section title="3. How We Use Your Information">
          <ul className="list-disc list-inside space-y-2 pl-2">
            <li>Authenticate you and sync your data across devices</li>
            <li>Calculate and display bill splits, balances, and settlement totals</li>
            <li>Generate Venmo payment links with itemized descriptions</li>
            <li>Send event invitations by email to people you invite</li>
            <li>Allow friends you add to view shared bills and events</li>
            <li>Improve app features and fix bugs using anonymized analytics</li>
          </ul>
          <p>We do not use your data for advertising, and we do not sell it to anyone.</p>
        </Section>

        {/* 4 */}
        <Section title="4. Receipt Images and AI Processing">
          <p>
            When you upload a receipt photo, it is sent to{' '}
            <span className="text-slate-200">Google Gemini AI</span> to automatically
            extract items and prices. The image is also stored in Firebase Cloud Storage so
            you can view it later within the app.
          </p>
          <p>
            Receipt images may contain information visible on your receipt (e.g., restaurant
            name, date, amounts). Only the extracted bill data is permanently stored in your
            account — you can delete the image at any time, which removes it from storage.
          </p>
          <p>
            Google's use of data sent to Gemini is governed by{' '}
            <span className="text-slate-200">Google's AI/ML Privacy Notice</span>. We do
            not use receipt images to train any models.
          </p>
        </Section>

        {/* 5 */}
        <Section title="5. Third-Party Services">
          <p>Divit relies on the following services, each with their own privacy practices:</p>
          <div className="space-y-4 pl-2">
            <div>
              <p className="font-medium text-slate-200">Firebase (Google)</p>
              <p>
                Handles authentication, database (Firestore), file storage, cloud functions,
                and analytics. Data is stored in Google data centers. See Google's{' '}
                <span className="text-slate-300">Firebase Privacy and Security</span>{' '}
                documentation for details.
              </p>
            </div>
            <div>
              <p className="font-medium text-slate-200">Google Gemini AI</p>
              <p>
                Processes receipt images to extract bill data. Images are sent to Google's
                servers for analysis and are not stored by Divit beyond what you see in the
                app.
              </p>
            </div>
            <div>
              <p className="font-medium text-slate-200">Venmo</p>
              <p>
                Divit generates Venmo deep links that open the Venmo app on your device. We
                do not have access to your Venmo account, password, or transaction history.
                Venmo handles all payment processing independently.
              </p>
            </div>
            <div>
              <p className="font-medium text-slate-200">Vercel</p>
              <p>
                Hosts the Divit web app. Standard server logs (including IP addresses) may
                be retained by Vercel per their privacy policy.
              </p>
            </div>
          </div>
        </Section>

        {/* 6 */}
        <Section title="6. Data Sharing">
          <p>Your data is shared only in these limited cases:</p>
          <ul className="list-disc list-inside space-y-2 pl-2">
            <li>
              <span className="text-slate-200">With friends you explicitly add</span> —
              linked friends can see shared bills and balances
            </li>
            <li>
              <span className="text-slate-200">With event members</span> — people in a
              group event can see all bills within that event
            </li>
            <li>
              <span className="text-slate-200">Via share links</span> — anyone with a
              share code can view and contribute to a bill (codes expire after 7 days)
            </li>
            <li>
              <span className="text-slate-200">With third-party services</span> listed in
              Section 5, as required to operate the app
            </li>
          </ul>
          <p>We never sell your data. We never share it for advertising purposes.</p>
        </Section>

        {/* 7 */}
        <Section title="7. Data Retention">
          <ul className="list-disc list-inside space-y-2 pl-2">
            <li>
              <span className="text-slate-200">Bills and events</span> — kept until you
              delete them
            </li>
            <li>
              <span className="text-slate-200">Receipt images</span> — kept until you delete
              the receipt or the bill
            </li>
            <li>
              <span className="text-slate-200">Settlement records</span> — kept
              indefinitely as an immutable history (like a bank statement)
            </li>
            <li>
              <span className="text-slate-200">Account data</span> — kept until you delete
              your account. To request deletion, email us at{' '}
              <a href={`mailto:${CONTACT_EMAIL}`} className="text-indigo-400 hover:underline">
                {CONTACT_EMAIL}
              </a>
            </li>
          </ul>
        </Section>

        {/* 8 */}
        <Section title="8. Your Rights and Choices">
          <ul className="list-disc list-inside space-y-2 pl-2">
            <li>
              <span className="text-slate-200">Access</span> — you can view all your data
              directly in the app
            </li>
            <li>
              <span className="text-slate-200">Edit</span> — update your profile, friends,
              and Venmo handle anytime in Settings
            </li>
            <li>
              <span className="text-slate-200">Delete bills</span> — delete any bill from
              the Dashboard; this permanently removes it and reverses any balances it
              affected
            </li>
            <li>
              <span className="text-slate-200">Delete your account</span> — email us and we
              will delete your account and associated data within 30 days
            </li>
            <li>
              <span className="text-slate-200">Opt out of analytics</span> — use a browser
              that blocks Google Analytics, or contact us to request exclusion
            </li>
          </ul>
          <p>
            If you are in the European Economic Area or California, you may have additional
            rights (access, portability, erasure, restriction). Contact us to exercise them.
          </p>
        </Section>

        {/* 9 */}
        <Section title="9. Security">
          <p>
            All data is transmitted over HTTPS. Firestore security rules ensure each user
            can only read and write their own data, and shared data is restricted to
            explicitly authorized participants. Receipt images are stored in Firebase Cloud
            Storage with access controls tied to your account.
          </p>
          <p>
            No method of transmission or storage is 100% secure. If you discover a
            vulnerability, please report it to{' '}
            <a href={`mailto:${CONTACT_EMAIL}`} className="text-indigo-400 hover:underline">
              {CONTACT_EMAIL}
            </a>
            .
          </p>
        </Section>

        {/* 10 */}
        <Section title="10. Children">
          <p>
            Divit is not directed at children under 13. We do not knowingly collect personal
            information from anyone under 13. If you believe a child under 13 has provided
            us with personal information, please contact us and we will delete it promptly.
          </p>
        </Section>

        {/* 11 */}
        <Section title="11. Changes to This Policy">
          <p>
            When we make material changes, we will update the "Last updated" date at the top
            of this page. Continued use of Divit after changes means you accept the updated
            policy.
          </p>
        </Section>

        {/* 12 */}
        <Section title="12. Contact Us">
          <p>Questions, requests, or concerns about this policy:</p>
          <p>
            <a
              href={`mailto:${CONTACT_EMAIL}`}
              className="text-indigo-400 hover:underline font-medium"
            >
              {CONTACT_EMAIL}
            </a>
          </p>
        </Section>

        <div className="h-px bg-slate-800" />

        <p className="text-sm text-slate-600 text-center pb-8">
          © {new Date().getFullYear()} Divit. All rights reserved.
        </p>
      </main>
    </div>
  );
}
